/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Governance__factory } from "./Governance__factory";
export { GovernanceToken__factory } from "./GovernanceToken__factory";
